### PR TITLE
FileUploader

### PR DESCRIPTION
**Pull request by WangBoxue**
Implement a component to upload file.
Usage: <FileUploader maxSize="1024000" minSize="1024" acceptTypes={["js", "jpg"]} afterUpload={this.afterUpload}></FileUploader>
 afterUpload(result){
    console.log(result.result);
    console.log(result.error);
    console.log(result.file);
 },

### CODE REVIEW

**Comment by LeonLiuY** [comment]
Please assign this PR to someone you want.

**Comment by RonaldoLee** [comment]
@WangBoxue Could you make a sample page to demonstrate the usage?
By the way, I think to restrict the minimal size of an uploading file is not nature, max is enough, what do you think?

**Comment by WangBoxue** [comment]
@RonaldoLee I add a sample page.
Min size is used to filter some wrong files if we know the minimal size of this kind of files. Min size is 0 by default. I add this property in case of future usage.

**Comment by WangBoxue** [comment]
@RonaldoLee  http://localhost:8000/platform/test

**Pull request merged**
