### PR TITLE
post resource

### PR DESCRIPTION
**Pull request by WangBoxue**

### CODE REVIEW

**Comment by RonaldoLee** [comment]
You can use the webfont instead of images, please check the icon examples at app/icons/demo.html. @WangBoxue

**Comment by WangBoxue** [comment]
@RonaldoLee done

**Comment by WangBoxue** [comment]
image
@RonaldoLee Remove background color and add border if there are pictures.

**Comment by RonaldoLee** [comment]
@WangBoxue  You can remove left.png & right.png.

**Comment by WangBoxue** [comment]
@RonaldoLee done

**Pull request merged**
